package ar.kennedy.is2011.db.dao;

import ar.kennedy.is2011.db.entities.User;
import ar.kennedy.is2011.db.entities.Account;
import ar.kennedy.is2011.db.exception.EntityNotFoundException;

import com.google.appengine.api.datastore.Key;

import java.util.List;

import org.apache.log4j.Logger;



public class AccountDao {

	//private static final Logger log = Logger.getLogger(AbstractDao.class);

	private AbstractDao<User> userDAO = new AbstractDao<User>();

	private User user;

	private Account account;
	private List<Account> accounts;


	public AccountDao() {
		// TODO Auto-generated constructor stub
	}

	public AccountDao(User us) {
		// TODO Auto-generated constructor stub
		this();
		setUser(us);
	}

	public User fetchUserById(Key key){
		if(key==null) return null;
		try {
			return (userDAO.findById(User.class, key.getId()));
			
		} catch(EntityNotFoundException e) {
			return null;
		}
	}

	/**  === AUTOGENERATEDE GETTERS - SETTERS: END ========  */
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public List<Account> getAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}

	/**  === AUTOGENERATEDE GETTERS - SETTERS: END ========  */

	
}
