package ar.kennedy.is2011.db.dao;

import ar.kennedy.is2011.db.entities.Article;
import ar.kennedy.is2011.db.entities.Task;
import ar.kennedy.is2011.db.entities.PictureEy;
import ar.kennedy.is2011.db.entities.EntityRelationHeader;
import ar.kennedy.is2011.models.RelationModel.LocationRelation;
import ar.kennedy.is2011.models.RelationModel.TaskRelation;
import ar.kennedy.is2011.models.RelationModel.PicturesRelation;

import java.util.List;

import org.apache.log4j.Logger;



public class ArticlePortlet {

	private static final Logger log = Logger.getLogger(AbstractDao.class);

	
	private Article article;
	private Task task;
	private PictureEy picture;
	private PictureEy pictureBranding;
	private EntityRelationHeader erelation;
	private List<LocationRelation> locations;
	private List<TaskRelation> taskrelations;
	private List<PicturesRelation> pictures;


	public ArticlePortlet() {
		// TODO Auto-generated constructor stub
	}


	/**  === AUTOGENERATEDE GETTERS - SETTERS: BEGIN ========  */

	public Article getArticle() {
		return article;
	}


	public void setArticle(Article article) {
		this.article = article;
	}


	public PictureEy getPicture() {
		return picture;
	}


	public void setPicture(PictureEy picture) {
		this.picture = picture;
	}


	public EntityRelationHeader getErelation() {
		return erelation;
	}


	public void setErelation(EntityRelationHeader erelation) {
		this.erelation = erelation;
	}

	
	
	public List<LocationRelation> getLocations() {
		return locations;
	}


	public void setLocations(List<LocationRelation> locations) {
		this.locations = locations;
	}


	public List<PicturesRelation> getPictures() {
		return pictures;
	}


	public void setPictures(List<PicturesRelation> pictures) {
		this.pictures = pictures;
	}


	public PictureEy getPictureBranding() {
		return pictureBranding;
	}


	public void setPictureBranding(PictureEy pictureBranding) {
		this.pictureBranding = pictureBranding;
	}


	public Task getTask() {
		return task;
	}


	public void setTask(Task task) {
		this.task = task;
	}


	public List<TaskRelation> getTaskrelations() {
		return taskrelations;
	}


	public void setTaskrelations(List<TaskRelation> taskrelations) {
		this.taskrelations = taskrelations;
	}



	/**  === AUTOGENERATEDE GETTERS - SETTERS: END ========  */


	
}
