package ar.kennedy.is2011.db.dao;

import ar.kennedy.is2011.db.entities.Article;
import ar.kennedy.is2011.db.entities.EntityRelations;
import ar.kennedy.is2011.db.entities.PersonaFisica;
import ar.kennedy.is2011.db.entities.PersonaIdeal;
import ar.kennedy.is2011.db.entities.PictureEy;
import ar.kennedy.is2011.db.entities.Task;
import ar.kennedy.is2011.db.entities.EntityRelationHeader;



//import org.apache.log4j.Logger;



public class EntityDao {

	//private static final Logger log = Logger.getLogger(AbstractDao.class);

	private PersonDao perDao;
	private ArticleDao artDao;
	private PictureDao picDao;
	private TaskDao taskDao;
	

	public EntityDao() {
		// TODO Auto-generated constructor stub
	}

	public PersonaFisica fetchFperson(EntityRelationHeader erh){
		if(!erh.getEntityType().equals("PF")) return null;
		return personDao().fetchFpersonById(erh.getEntityId());		
	}
	
	public PersonaIdeal fetchIperson(EntityRelationHeader erh){
		if(!erh.getEntityType().equals("PI")) return null;
 		return personDao().fetchIpersonById(erh.getEntityId());		
	}
	
	public Article fetchArticle(EntityRelationHeader erh){
		if(!erh.getEntityType().equals("ARTICLE")) return null;
		return articleDao().fetchArticle(erh.getEntityId());		
	}

	public Task fetchTask(EntityRelationHeader erh){
		if(!erh.getEntityType().equals("TASK")) return null;
		return taskDao().fetchTask(erh.getEntityId());		
	}

	
	public PictureEy fetchPicture(EntityRelations eitem){
		if(!eitem.getEntityType().equals("PICTURE")) return null;
		return pictureDao().fetchPicture(eitem.getPictureId());		
	}


	/**  === AUTOGENERATEDE GETTERS - SETTERS: BEGIN ======  */

	
	public PersonDao personDao() {
		if(this.perDao==null) this.perDao=new PersonDao();
		return this.perDao;
	}



	public ArticleDao articleDao() {
		if(this.artDao==null) this.artDao=new ArticleDao();
		return this.artDao;
	}

	public TaskDao taskDao() {
		if(this.taskDao==null) this.taskDao=new TaskDao();
		return this.taskDao;
	}


	public PictureDao pictureDao() {
		if(this.picDao==null) this.picDao=new PictureDao();
		return this.picDao;
	}

	
	
	
	
	
	/**  === AUTOGENERATEDE GETTERS - SETTERS: END ========  */

	
}
