package ar.kennedy.is2011.models;

import ar.kennedy.is2011.db.dao.ArticleDao;
import ar.kennedy.is2011.db.entities.User;
import ar.kennedy.is2011.db.entities.Article;


import ar.kennedy.is2011.utils.WebUtils;

import com.google.appengine.api.datastore.Key;
//import com.google.appengine.api.datastore.KeyFactory;

import java.util.List;
import java.util.Date;



public class ArticleModel extends AbstractModel {


	//private static final String ALL_IPERSONS =    "SELECT e FROM PersonaIdeal e ";	

	//private static final String IPERSON_BY_NAME = "SELECT e FROM PersonaIdeal e WHERE e.nombrePerson = :1";
	//private static final String ALL_IPERSONS =    "SELECT e FROM PersonaIdeal e ";	

	private static final Integer ACTIVE = 1;
	
	private User user;
	private Article article;
	private List<Article> articles;
	private ArticleDao articleDao;
	
	
	public ArticleModel() {
		// TODO Auto-generated constructor stub
		super();
		articleDao = new ArticleDao();
	}
	public ArticleModel(User us) {
		this();
		setUser(us);
		articleDao = new ArticleDao(us);
	}

	public void updateArticle(){
		articleDao.update(getArticle());

	}


	public Article fetchArticle(Key key){
		return articleDao.fetchArticle(key);
	}

	public Article fetchArticle(Long id){
		return articleDao.fetchArticle(id);
	}

	public Article selectArticle(Key key){
		setArticle(fetchArticle(key));
		return getArticle();
	}

	public Article selectArticle(Long id){
		setArticle(fetchArticle(id));
		return getArticle();
	}
	
	public Article selectArticle(String id){
		if(WebUtils.isNull(id)) return null;
		setArticle(fetchArticle(Long.parseLong(id)));
		return getArticle();
	}

	public void initNewArticle(){
		setArticle(new Article());
		getArticle().setCdate(new Date());
		getArticle().setUdate(getArticle().getCdate());
		getArticle().setIsActive(ACTIVE);
		getArticle().setVisibility(1);
		getArticle().setType("ARTICULO");
		getArticle().setSection("GENERICO");
		getArticle().setOwner(getUser().getKey());
	}
	
	/**  === AUTOGENERATEDE GETTERS - SETTERS: BEGIN ======  */
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	public Article getArticle() {
		return article;
	}
	public void setArticle(Article article) {
		this.article = article;
	}
	public List<Article> getArticles() {
		return articles;
	}
	public void setArticles(List<Article> articles) {
		this.articles = articles;
	}
	public ArticleDao getArticleDao() {
		return articleDao;
	}
	public void setArticleDao(ArticleDao articleDao) {
		this.articleDao = articleDao;
	}
	/**  === AUTOGENERATEDE GETTERS - SETTERS: END ========  */
	

}
