package ar.kennedy.is2011.db.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Basic;
import com.google.appengine.api.datastore.Text;

import java.util.Date;

import ar.kennedy.is2011.utils.WebUtils;

import com.google.appengine.api.datastore.Key;

/**
 * @author mgo
 */

@Entity
@Table(name = "ARTICLE")
public class Article implements Serializable {

	private static final long serialVersionUID = 7596454954378729377L;
	//private final String[] locTypes ={"GENERICA","ALBUM","GRUPO"};

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
	
	@Column(name = "NAME", length=50)
	private String name;

	@Column(name = "MAIN_TITLE", length=80)
	private String mainTitle;

	@Column(name = "SECOND_TITLE", length=120)
	private String secondTitle;

	@Column(name = "SLUG", length=80)
	private String slug;

	@Column(name = "TEXT", length=1500)
	private Text text;

	@Column(name = "VISIBILITY")
	private Integer visibility;

	@Column(name = "ACTIVE")
	private Integer isActive;

	@Column(name = "OWNER")
	@Basic()
    private Key owner;
	
	@Column(name = "TYPE")
    private String type;

	@Column(name = "SECTION")
    private String section;

	@Column(name = "RENDERING")
    private String rendering;
	
	@Column(name = "UDATE")
    private Date udate;

	@Column(name = "CDATE")
    private Date cdate;

	@Column(name = "PBDATE")
    private Date publishFromDate;
	
	@Column(name = "PEDATE")
    private Date publishUpToDate;
	
	public Article() {
		super();
	}

	public String getId(){
		if(key==null) return "0";
		else return Long.toString(getKey().getId());
	}

	public String getPublishFromDateAsText() {
		return WebUtils.getFormatedDate(getPublishFromDate());
	}
	public String getPublishToDateAsText() {
		return WebUtils.getFormatedDate(getPublishUpToDate());
	}
	
	public String getTextData(){
		if(getText()==null) return "";
		return getText().getValue();
		
	}
	
	public String toString(){
		return getName();
		
	}

	
 	/** ======= Autogenerated Getters y Setters =========== */
	
	public Key getKey() {
		return key;
	}

	public void setKey(Key key) {
		this.key = key;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMainTitle() {
		return mainTitle;
	}

	public void setMainTitle(String mainTitle) {
		this.mainTitle = mainTitle;
	}

	public String getSecondTitle() {
		return secondTitle;
	}

	public void setSecondTitle(String secondTitle) {
		this.secondTitle = secondTitle;
	}

	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Text getText() {
		return text;
	}

	public void setText(Text text) {
		this.text = text;
	}

	public Integer getVisibility() {
		return visibility;
	}

	public void setVisibility(Integer visibility) {
		this.visibility = visibility;
	}

	public Integer getIsActive() {
		return isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	public Key getOwner() {
		return owner;
	}

	public void setOwner(Key owner) {
		this.owner = owner;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSection() {
		return section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	public String getRendering() {
		return rendering;
	}

	public void setRendering(String rendering) {
		this.rendering = rendering;
	}

	public Date getUdate() {
		return udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public Date getCdate() {
		return cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}



	public Date getPublishFromDate() {
		return publishFromDate;
	}



	public void setPublishFromDate(Date publishFromDate) {
		this.publishFromDate = publishFromDate;
	}



	public Date getPublishUpToDate() {
		return publishUpToDate;
	}



	public void setPublishUpToDate(Date publishUpToDate) {
		this.publishUpToDate = publishUpToDate;
	}

 	/** ======= Autogenerated Getters y Setters =========== */
	
}