package ar.kennedy.is2011.db.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Basic;
import com.google.appengine.api.datastore.Text;

import java.util.Date;

import ar.kennedy.is2011.utils.WebUtils;

import com.google.appengine.api.datastore.Key;

/**
 * @author mgo
 */

@Entity
@Table(name = "ROLEPLAYING")
public class RolePlaying implements Serializable {

	private static final long serialVersionUID = 7596454954378729377L;
	//private final String[] locTypes ={"GENERICA","ALBUM","GRUPO"};

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
	
	@Column(name = "NAME", length=30)
	private String name;
	
	@Column(name = "VOTED")
    private Boolean hasVoted;
	
	@Column(name = "ELECTED")
    private Boolean hasBeenElected;

	@Column(name = "VOTEDATE")
    private Date voteDate;

	@Column(name = "VOTEID")
    private Long  voteId;

	
	public RolePlaying() {
		super();
	}

	public RolePlaying(String person) {
		super();
		setName(person);
	}


	public String getId(){
		if(key==null) return "0";
		else return Long.toString(getKey().getId());
	}

	public String getVotedDateAsText() {
		return WebUtils.getFormatedDate(getVoteDate());
	}

		
	public String toString(){
		return getName();
		
	}

	public Key getKey() {
		return key;
	}

	public void setKey(Key key) {
		this.key = key;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getHasVoted() {
		return hasVoted;
	}

	public void setHasVoted(Boolean hasVoted) {
		this.hasVoted = hasVoted;
	}

	public Boolean getHasBeenElected() {
		return hasBeenElected;
	}

	public void setHasBeenElected(Boolean hasBeenElected) {
		this.hasBeenElected = hasBeenElected;
	}

	public Date getVoteDate() {
		return voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

	public Long getVoteId() {
		return voteId;
	}

	public void setVoteId(Long voteId) {
		this.voteId = voteId;
	}

	
 	/** ======= Autogenerated Getters y Setters =========== */
	

	
	
	
	/** ======= Autogenerated Getters y Setters =========== */
	
}