package ar.kennedy.is2011.db.entities;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.google.appengine.api.datastore.Key;

/**
 * @author mgo
 */
@Entity
@Table(name = "TAG")
public class TagEntry implements Serializable {

	private static final long serialVersionUID = 7596454954378729377L;
	//private final String[] tagTypes ={"GENERICA","ALBUM","GRUPO"};
	//private final String[] entityTypes ={"PICTURE","PF","PI","REL"};

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
	
	@Column(name = "TAGKEY")
	@Basic()
	private Key tagKey;

	@Column(name = "ENTITY")
	private String entityType;

	@Column(name = "ENTITYKEY")
	@Basic()
	private Key entityKey;

	@Column(name = "ACTIVE")
	private Integer isActive;
	
	@Column(name = "OWNER")
	@Basic()
    private Key owner;
		
	public TagEntry() {
		super();
	}

	public Key getKey() {
		return key;
	}
	public void setKey(Key key) {
		this.key = key;
	}
	public Key getTagKey() {
		return tagKey;
	}
	public void setTagKey(Key tagKey) {
		this.tagKey = tagKey;
	}
	public String getEntityType() {
		return entityType;
	}
	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}
	public Key getEntityKey() {
		return entityKey;
	}
	public void setEntityKey(Key entityKey) {
		this.entityKey = entityKey;
	}
	public Integer getIsActive() {
		return isActive;
	}
	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}
	public Key getOwner() {
		return owner;
	}
	public void setOwner(Key owner) {
		this.owner = owner;
	}

	/** ======= Autogenerated Getters y Setters =========== */

	
}