package ar.kennedy.is2011.db.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Basic;
import com.google.appengine.api.datastore.Text;

import java.util.Date;

import ar.kennedy.is2011.utils.WebUtils;

import com.google.appengine.api.datastore.Key;

/**
 * @author mgo
 */

@Entity
@Table(name = "TASK")
public class Task implements Serializable {

	private static final long serialVersionUID = 7596454954378729377L;
	//private final String[] locTypes ={"GENERICA","ALBUM","GRUPO"};
	
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Key key;
	
	@Column(name = "LOCATOR", length=40)
	private String locator;

	@Column(name = "SUBJECT", length=80)
	private String subject;

	@Column(name = "TEXT", length=1500)
	private Text text;

	@Column(name = "VISIBILITY")
	private Integer visibility;

	@Column(name = "ACTIVE")
	private Integer isActive;

	@Column(name = "STATUS")
	private Integer status;

	@Column(name = "ASSIGNEE")
	private Key asignee;

	@Column(name = "OWNER")
	@Basic()
    private Key owner;

	@Column(name = "BEGINDATE")
    private Date begindate;

	@Column(name = "DUEDATE")
    private Date duedate;

	@Column(name = "TYPE")
    private String type;

	@Column(name = "PROJECT")
    private String project;

	@Column(name = "RENDERING")
    private String rendering;
	
	@Column(name = "UDATE")
    private Date udate;

	@Column(name = "CDATE")
    private Date cdate;
	
	public Task() {
		super();
	}

	public String getId(){
		if(key==null) return "0";
		else return Long.toString(getKey().getId());
	}

	public String getDueDateAsText() {
		return WebUtils.getFormatedDate(getDuedate());
	}

	public String getBeginDateAsText() {
		return WebUtils.getFormatedDate(getBegindate());
	}
	
	
	public String getTextData(){
		if(getText()==null) return "";
		return getText().getValue();
	}
	
	public String toString(){
		return getSubject();	
	}
	
	
 	/** ======= Autogenerated Getters y Setters =========== */
	public Key getKey() {
		return key;
	}

	public void setKey(Key key) {
		this.key = key;
	}

	public String getLocator() {
		return locator;
	}

	public void setLocator(String locator) {
		this.locator = locator;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Text getText() {
		return text;
	}

	public void setText(Text text) {
		this.text = text;
	}

	public Integer getVisibility() {
		return visibility;
	}

	public void setVisibility(Integer visibility) {
		this.visibility = visibility;
	}

	public Integer getIsActive() {
		return isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Key getAsignee() {
		return asignee;
	}

	public void setAsignee(Key assignee) {
		this.asignee = assignee;
	}

	public Key getOwner() {
		return owner;
	}

	public void setOwner(Key owner) {
		this.owner = owner;
	}

	public Date getDuedate() {
		return duedate;
	}

	public void setDuedate(Date duedate) {
		this.duedate = duedate;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getProject() {
		return project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getRendering() {
		return rendering;
	}

	public void setRendering(String rendering) {
		this.rendering = rendering;
	}

	public Date getUdate() {
		return udate;
	}

	public void setUdate(Date udate) {
		this.udate = udate;
	}

	public Date getCdate() {
		return cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public Date getBegindate() {
		if(begindate==null) return getDuedate();
		return begindate;
	}

	public void setBegindate(Date begindate) {
		this.begindate = begindate;
	}	
	
	
 	/** ======= Autogenerated Getters y Setters =========== */
	
}